version: '3.8'

services:
  backend:
    build:
      context: ./node-express-server
    ports:
      - "8080:8080"
    volumes:
      - ./node-express-server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./react-client
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

