name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Backend Container
        run: |
          docker build -t backend-image ./node-express-server
  
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Frontend Container
        run: |
          docker build -t frontend-image ./react-client

  run_tests:
    needs: [build_backend, build_frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Backend Unit Tests
        run: |
          docker run --rm backend-image npm test
      
      - name: Run Frontend Unit Tests
        run: |
          docker run --rm frontend-image npm test

  lint_and_sast:
    needs: [build_backend, build_frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Lint Backend Code
        run: |
          docker run --rm backend-image npm run lint
      
      - name: Lint Frontend Code
        run: |
          docker run --rm frontend-image npm run lint
      
      - name: Run SAST Scan
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

  push_to_dockerhub:
    needs: [run_tests, lint_and_sast]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Backend Container
        run: |
          docker tag backend-image ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
      
      - name: Push Frontend Container
        run: |
          docker tag frontend-image ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

